CONFIG_TFM_PROFILE_TYPE_NOT_SET=y
CONFIG_TFM_SPM_LOG_LEVEL_DEBUG=y
CONFIG_TFM_EXCEPTION_INFO_DUMP=y
CONFIG_TFM_PARTITION_LOG_LEVEL_DEBUG=y

CONFIG_PPI_TRACE=y

CONFIG_REBOOT=n
CONFIG_PRINTK=y
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_HW_STACK_PROTECTION=y
CONFIG_RUNTIME_ERROR_CHECKS=y
CONFIG_FAULT_DUMP=2
